# Generated by Django 3.2.5 on 2021-11-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocation',
            old_name='name',
            new_name='info',
        ),
    ]
